# Generated by Django 4.1.1 on 2022-10-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitantes', '0003_solicitante_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pecosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_pecosa', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('creacion_pecosa', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificacion_pecosa', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitantes.solicitante')),
            ],
            options={
                'verbose_name': 'pecosa',
                'verbose_name_plural': 'pecosas',
            },
        ),
    ]
