# Generated by Django 4.1.1 on 2022-10-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0002_pecosamaterial_pecosa_matpecosa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecosa',
            name='matpecosa',
        ),
    ]
