# Generated by Django 4.1.1 on 2022-10-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_categoria_descripcion_categoria_and_more'),
        ('pecosas', '0003_remove_pecosa_matpecosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecosa',
            name='matpecosa',
            field=models.ManyToManyField(through='pecosas.PecosaMaterial', to='materiales.material'),
        ),
    ]
