# Generated by Django 4.0.6 on 2022-10-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0005_pecosa_codigo_pecosa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecosa',
            name='codigo_pecosa',
        ),
    ]
