# Generated by Django 4.0.6 on 2022-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0006_remove_pecosa_codigo_pecosa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_entrada', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_merma', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'merma',
                'verbose_name_plural': 'mermas',
            },
        ),
        migrations.AddField(
            model_name='pecosa',
            name='codigo_pecosa',
            field=models.CharField(max_length=50, null=True, verbose_name='CTA contable'),
        ),
        migrations.AlterField(
            model_name='pecosa',
            name='descripcion_pecosa',
            field=models.TextField(verbose_name='Justificación'),
        ),
    ]
