# Generated by Django 4.0.6 on 2022-10-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0004_alter_solicitante_area_and_more'),
        ('pecosas', '0007_entrada_merma_pecosa_codigo_pecosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecosa',
            name='codigo_pecosa',
            field=models.CharField(max_length=50, verbose_name='CTA contable'),
        ),
        migrations.AlterField(
            model_name='pecosa',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitantes.solicitante'),
        ),
    ]
