# Generated by Django 4.0.6 on 2022-10-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_material_nombre_material'),
        ('pecosas', '0009_mermamaterial_entradamaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='matentrada',
            field=models.ManyToManyField(through='pecosas.EntradaMaterial', to='materiales.material'),
        ),
        migrations.AddField(
            model_name='merma',
            name='matmerma',
            field=models.ManyToManyField(through='pecosas.MermaMaterial', to='materiales.material'),
        ),
    ]
