# Generated by Django 4.0.6 on 2022-10-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0010_entrada_matentrada_merma_matmerma'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='creacion_entrada',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='modificacion_entrada',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='merma',
            name='creacion_merma',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='merma',
            name='modificacion_merma',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
