# Generated by Django 4.0.6 on 2022-10-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0011_entrada_creacion_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='descripcion_entrada',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
