# Generated by Django 4.0.6 on 2022-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0016_alter_entrada_id_alter_entradamaterial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecosa',
            name='codigo_pecosa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CTA contable'),
        ),
    ]
