# Generated by Django 4.1.1 on 2022-10-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0017_alter_pecosa_codigo_pecosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecosa',
            name='precio_total_pecosa',
            field=models.IntegerField(null=True, verbose_name='Precio total'),
        ),
        migrations.AddField(
            model_name='pecosamaterial',
            name='precio_total_material',
            field=models.IntegerField(null=True, verbose_name='Precio total del material'),
        ),
    ]
