# Generated by Django 4.1.1 on 2022-11-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0018_pecosa_precio_total_pecosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecosa',
            name='precio_total_pecosa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='pecosamaterial',
            name='precio_total_material',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio total del material'),
        ),
    ]
