# Generated by Django 4.1.1 on 2022-11-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0019_alter_pecosa_precio_total_pecosa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecosa',
            name='codigo_pecosa',
        ),
    ]
