# Generated by Django 4.1.1 on 2022-11-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0022_remove_pecosa_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecosa',
            name='precio_total_pecosa',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='pecosamaterial',
            name='precio_total_material',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Precio total del material'),
        ),
    ]
