# Generated by Django 4.1.1 on 2022-11-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0023_alter_pecosa_precio_total_pecosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecosa',
            name='precio_total_pecosa',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Precio total pecosa'),
        ),
        migrations.AlterField(
            model_name='pecosamaterial',
            name='pecosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidad', to='pecosas.pecosa'),
        ),
    ]
