# Generated by Django 4.1.1 on 2022-11-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pecosas', '0024_alter_pecosa_precio_total_pecosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecosamaterial',
            name='pecosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecosas.pecosa'),
        ),
    ]
