# Generated by Django 4.1.1 on 2022-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_categoria', models.TextField(verbose_name='Descripcion')),
                ('creacion_categoria', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificacion_categoria', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
