# Generated by Django 4.1.1 on 2022-10-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion_material', models.TextField(verbose_name='Descripción')),
                ('stock_material', models.IntegerField(verbose_name='stock')),
                ('creacion_material', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificacion_material', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('categoria_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
