# Generated by Django 4.1.1 on 2022-10-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion_categoria',
        ),
        migrations.RemoveField(
            model_name='material',
            name='descripcion_material',
        ),
    ]
