# Generated by Django 4.0.6 on 2022-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_categoria_descripcion_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=150, verbose_name='Nombre')),
                ('creacion_unidad', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificacion_unidad', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='codigo_material',
            field=models.CharField(max_length=50, null=True, verbose_name='Código de Repuesto'),
        ),
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.CharField(max_length=200, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='material',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Precio unitario'),
        ),
        migrations.AddField(
            model_name='material',
            name='ubicacion_material',
            field=models.CharField(max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
