# Generated by Django 4.0.6 on 2022-10-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_unidad_material_codigo_material_material_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='nombre_material',
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_material',
            field=models.CharField(max_length=50, verbose_name='Código de Repuesto'),
        ),
        migrations.AlterField(
            model_name='material',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ubicacion_material',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
    ]
