# Generated by Django 4.0.6 on 2022-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_alter_material_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nombre_material',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
