# Generated by Django 4.0.6 on 2022-10-18 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_material_nombre_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.unidad', verbose_name='Unidad'),
        ),
    ]
