# Generated by Django 4.1.1 on 2022-11-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0010_alter_categoria_id_alter_material_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='creacion_material',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='modificacion_material',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación'),
        ),
    ]
