# Generated by Django 4.1.1 on 2022-11-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0011_alter_material_creacion_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='creacion_material',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='modificacion_material',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificación'),
        ),
    ]
