# Generated by Django 4.1.1 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0012_alter_material_creacion_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Precio unitario'),
        ),
    ]
