# Generated by Django 4.1.1 on 2022-11-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0013_alter_material_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidad_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.unidad', verbose_name='Unidad'),
        ),
    ]
