# Generated by Django 4.1.1 on 2022-10-12 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0002_area_remove_solicitante_descripcion_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitantes.area'),
        ),
    ]
