# Generated by Django 4.0.6 on 2022-10-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0003_solicitante_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitantes.area'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='telefono_solicitante',
            field=models.CharField(max_length=13, verbose_name='telefono'),
        ),
    ]
